# Generated by Django 3.2 on 2022-08-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
